config/routes.rb
Rails.application.routes.draw do
  root 'pages#index'
  get 'courses/new', to: 'courses#new'
  get 'courses/index', to: 'courses#index'
  get 'about' , to: 'pages#about'
  resources :students, except: [:destroy]
  get 'login' , to: 'logins#new'
  post 'login' , to: 'logins#create'
  delete 'logout' , to: 'logins#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/course.rb
class Course < ApplicationRecord
  validates :name, presence: true, length: {minimum: 5,maximum: 50}
end

app/models/student.rb
class Student < ApplicationRecord
  before_save { self.email = email.downcase } 
  validates :name, presence: true, length: {minimum: 5,maximum: 50}
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 105 },
             uniqueness: { case_sensitive: false },
             format: { with: VALID_EMAIL_REGEX }
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :require_user
  helper_method :current_user, :logged_in?
  def current_user 
    @current_user ||= Student.find(session[:student_id]) if session[:student_id]
  end

  def logged_in? 
    !!current_user
  end

  def require_user
    if !logged_in?
      flash[:notice] = "You must be logged in to perform that action"
      redirect_to login_path 
    else

    end
  end
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  skip_before_action :require_user
  def index
    @courses = Course.all
  end

  def new

  end
  
end

app/controllers/logins_controller.rb
class LoginsController < ApplicationController
  skip_before_action :require_user, only: [:new,:create]
  def new

  end

  def create
    student = Student.find_by(email: params[:logins][:email].downcase)
    if student && student.authenticate(params[:logins][:password])
      session[:student_id] = student.id
      flash[:notice] = "You have successfully logged in"
      redirect_to student
    else
      flash.now[:notice] = "Something was wrong with your login information"
      render 'new'
    end
  end

  def destroy
    session[:student_id] = nil
    flash[:notice] = "You have successfully logged out"
    redirect_to students_path
  end
  
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :require_user
  def about

  end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  skip_before_action :require_user, only: [:new, :create]
  before_action :set_student, only: [:show,:edit,:update]
  def index
    @students = Student.all
  end
  
  def show 

  end

  def new 
    @student = Student.new
  end

  def create
    @student = Student.new(student_params)
    if @student.save
      flash[:notice] = 'You have successfully signed up'
      redirect_to students_path
    else
      render 'new'
    end
  end

  def edit 

  end

  def update

    if @student.update(student_params)
      flash[:notice] = "You have successfully updated your profile"
      redirect_to student_path(@student)
    else
      render 'edit'
    end
  end

  private

  def set_student 
    @student = Student.find(params[:id])
  end

  def student_params
    params.require(:student).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def session_link
    if (logged_in?)
      link_to('Logout', logout_path, method: :delete)
    else 
      link_to('Login', login_path)
    end 
  end
end

app/views/courses/index.html.erb
<div class="carousel carousel-slider center">
  <div class="carousel-fixed-item center">
    <div class="carousel-buttons">
      <i class="carousel-b material-icons prev-btn">keyboard_arrow_left</i>
      <i class="carousel-b material-icons next-btn">keyboard_arrow_right</i>
    </div>
  </div>
  <div class="carousel-item red white-text first-carousel-item" href="#one!">
    <div class="carousel-text-block">
      <h2 class="carousel-header">Добро пожаловать!</h2>
      <p class="white-text">Хотите стать настоящим профессионалом? Вы на верном пути.</p>
      <i class="large material-icons">beenhere</i>
    </div>
  </div>
  <div class="carousel-item amber white-text second-carousel-item" href="#two!">
    <div class="carousel-text-block">
      <h2 class="carousel-header">Выбор за Вами!</h2>
      <p class="white-text">Тираспольский Техникум Информатики и Права предоставляет возможность обучаться в следующих сферах:</p>
      <div class="scopes">
        <div class="scope-1">
          <p class="white-text">Юрист</p>
          <i class="large material-icons">school</i>
        </div>
        <div class="scope-2">
          <p class="white-text">Программист</p>
          <i class="large material-icons">laptop_windows</i>
        </div>
      </div>
    </div>
  </div>
  <div class="carousel-item green white-text third-carousel-item" href="#three!">
    <div class="carousel-text-block">
      <h2 class="carousel-header">Будьте уверены</h2>
      <p class="white-text">Квалифицированный педагогический состав и дружный студенческий коллектив не дадут вам разочароваться в нас!</p>
      <i class="large material-icons">group</i>
    </div>
  </div>
  <div class="carousel-item blue white-text fourth-carousel-item" href="#four!">
    <div class="carousel-text-block">
      <h2 class="carousel-header">Заинтересованы?</h2>
      <p class="white-text">Если вам необходим современный взгляд на две самые востребованные профессии,свяжитесь с нами </p>
      <i class="large material-icons contacts">contacts</i>
    </div>
  </div>
</div>

app/views/courses/new.html.erb
<h1>this is new course page</h1>

app/views/layouts/_footer.html.erb
<footer class="page-footer grey darken-3">
    <div class="container">
      <div class="row">
        <div class="col l6 s12">
          <h5 class="white-text">Техникум Информатики и Права</h5>
          <p class="grey-text text-lighten-4">Адрес электронной почты: ttip2010@mail.ru</p>
        </div>
        <div class="col l4 offset-l2 s12">
          <h5 class="white-text">Больше информации</h5>
          <ul>
            <li><a class="grey-text text-lighten-3" href="#!">Link 1</a></li>
            <li><a class="grey-text text-lighten-3" href="#!">Link 2</a></li>
            <li><a class="grey-text text-lighten-3" href="#!">Link 3</a></li>
            <li><a class="grey-text text-lighten-3" href="#!">Link 4</a></li>
          </ul>
        </div>
      </div>
    </div>
    <div class="footer-copyright">
      <div class="container">
      © 2021 Copyright Text
      <a class="grey-text text-lighten-4 right" href="#!">More Links</a>
      </div>
    </div>
  </footer>

app/views/layouts/_navigation.html.erb
<nav class="nav-block">
  <div class="nav-wrapper grey darken-3">
    <a href="#" class="brand-logo">
      <%= image_tag("icon-wide.png", alt: "image", size: '80x50', class:"icon" ) %>
    </a>
    <a href="#" data-target="mobile-demo" class="sidenav-trigger"><i class="material-icons">menu</i></a>
      <ul id="nav-mobile" class="right hide-on-med-and-down">
        <li class="nav-li"><a href="#" class="nav-link">Courses</a></li>
        <li class="nav-li"><a href="#" class="nav-link">Enrollments</a></li>
        <li class="nav-li"><%= session_link %></li>
      </ul>
      <ul class="sidenav" id="mobile-demo">
        <li><a href="#">Courses</a></li>
        <li><a href="#">Enrollments</a></li>
        <li><a href="#">Account</a></li>
      </ul>
  </div>
</nav>

<% flash.each do  |key,message| %>
  <div class="container">
    <div class="row sign-up-form">
        <div class="col s12 m12 l12"> 
          <div class="card-panel red lighten-1" id="fade-out-target">
            <span class="white-text">
              <%= message %>
            </span>
          </div>
        </div>
    </div>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CollegeApp</title>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Spectral:wght@200&display=swap" rel="stylesheet">
    <%= csrf_meta_tags %>
    <%= favicon_link_tag '/public/favicon.ico' %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main>
      <%= yield %>
    </main>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/logins/new.html.erb
<div class="container">
    <div class="row center sign-up-form">
      <div class="col s12 m12 l12"> 
        <div class="card-panel">
          <h3 class="text-center">Log in</h3>
          <div class="row padding-bottom">
            <%= form_for( :logins, html: {class: "col s12"}) do |f| %>
              <div class="row">
                <div class="input-field col s12">
                  <%= f.email_field :email, placeholder: "Enter your email address" %>
                  <%= f.label :email %>
                </div>
              </div>
              <div class="row">
                <div class="input-field col s12">
                  <%= f.password_field :password, placeholder: "Enter a password" %>
                  <%= f.label :password, class: "active" %>
                </div>
              </div>
              <%= f.button '<i class="material-icons right">arrow_forward</i>Log in'.html_safe, class: "btn waves-effect waves-light" %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>

app/views/pages/about.html.erb
<h1>This is about page</h1>

app/views/pages/index.html.erb
<div class="full-height">
  <div class="carousel carousel-slider center">
  <div class="carousel-fixed-item center">
    <div class="carousel-buttons">
      <i class="carousel-b material-icons prev-btn">keyboard_arrow_left</i>
      <i class="carousel-b material-icons next-btn">keyboard_arrow_right</i>
    </div>
  </div>
  <div class="carousel-item red white-text first-carousel-item" href="#one!">
    <div class="carousel-text-block">
      <h2 class="carousel-header">Добро пожаловать!</h2>
      <p class="white-text">Хотите стать настоящим профессионалом? Вы на верном пути.</p>
      <i class="large material-icons">beenhere</i>
    </div>
  </div>
  <div class="carousel-item amber white-text second-carousel-item" href="#two!">
    <div class="carousel-text-block">
      <h2 class="carousel-header">Выбор за Вами!</h2>
      <p class="white-text">Тираспольский Техникум Информатики и Права предоставляет возможность обучаться в следующих сферах:</p>
      <div class="scopes">
        <div class="scope-1">
          <p class="white-text">Юрист</p>
          <i class="large material-icons">school</i>
        </div>
        <div class="scope-2">
          <p class="white-text">Программист</p>
          <i class="large material-icons">laptop_windows</i>
        </div>
      </div>
    </div>
  </div>
  <div class="carousel-item green white-text third-carousel-item" href="#three!">
    <div class="carousel-text-block">
      <h2 class="carousel-header">Будьте уверены</h2>
      <p class="white-text">Квалифицированный педагогический состав и дружный студенческий коллектив не дадут вам разочароваться в нас!</p>
      <i class="large material-icons">group</i>
    </div>
  </div>
  <div class="carousel-item blue white-text fourth-carousel-item" href="#four!">
    <div class="carousel-text-block">
      <h2 class="carousel-header">Заинтересованы?</h2>
      <p class="white-text">Если вам необходим современный взгляд на две самые востребованные профессии,свяжитесь с нами </p>
      <i class="large material-icons contacts">contacts</i>
    </div>
  </div>
  </div>
</div>
 

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
  <div class="container">
    <div class="row sign-up-form">
      <div class="col s12 m12 l12"> 
        <div class="card-panel red lighten-1">
        <span class="white-text">
          <strong><%= pluralize(@student.errors.count, "error") %></strong>
            prohibited your profile from being created
          <ul>
            <% @student.errors.full_messages.each do |message| %>
            <li><%= message %></li>
            <% end %>
          </ul>
        </span>
      </div>
    </div>
  </div>
</div>
<% end %>

app/views/students/_form.html.erb
<div class="container padding-bottom">
  <%= render 'shared/errors', obj: @student %>
  <div class="container">
    <div class="row center sign-up-form">
      <div class="col s12 m12 l12"> 
        <div class="card-panel">
          <h3 class="text-center"><%= @student.new_record? ? "Sign up" : "Edit your profile" %></h3>
          <div class="row padding-bottom">
            <%= form_for( @student, html: {class: "col s12"}) do |f| %>
              <div class="row">
                <div class="input-field col s12">
                  <%= f.text_field :name, placeholder: "Enter your full name", autofocus: true %>
                  <%= f.label :name %>
                </div>
              </div>
              <div class="row">
                <div class="input-field col s12">
                  <%= f.email_field :email, placeholder: "Enter your email address" %>
                  <%= f.label :email, class: "active"%>
                </div>
              </div>
              <div class="row">
                <div class="input-field col s12">
                  <%= f.password_field :password, placeholder: "Choose a password" %>
                  <%= f.label :password, class: "active" %>
                </div>
              </div>
              <div class="row">
                <div class="input-field col s12">
                  <%= f.password_field :password_confirmation, placeholder: "Confirm a password" %>
                  <%= f.label :password_confirmation, class: "active" %>
                </div>
              </div>
              <%= f.button(@student.new_record? ? '<i class="material-icons right">arrow_forward</i>Sign up'.html_safe : '<i class="material-icons right">arrow_forward</i>Submit changes'.html_safe, class: "btn waves-effect waves-light") %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/students/edit.html.erb
<%= render 'form' %>

app/views/students/index.html.erb
<div class="container">
  <div class="row">
    <div class="col s12">
      <h3 class="text-center">Students Directory</h3>
    </div>
  </div>

  <div class="row">
  <% @students.each do |student| %>
    <div class="col s6 m6">
      <div class="card grey darken-3">
        <div class="card-content white-text">
          <span class="card-title">Name: <%= student.name%></span>
          <p>Email: <%= student.email%></p>
          <p>Course Enrollments: none</p>
        </div>
        <div class="card-action">
          <%= link_to 'View profile', students_path(student[:id]) %>
        </div>
      </div>
    </div>
    <% end %>
  </div>
</div>

app/views/students/new.html.erb
<%= render 'form' %>

app/views/students/show.html.erb
<div class="container">
  <div class="row padding-top">
    <div class="col s6 m6">
      <div class="card grey darken-3">
        <div class="card-content white-text">
          <span class="card-title">Name: <%= @student.name%></span>
          <p>Email: <%= @student.email%></p>
          <p>Course Enrollments: none</p>
        </div>
      </div>
      <%= link_to '<i class="material-icons right">edit</i>Edit your pofile'.html_safe, edit_student_path(@student), class:"waves-effect waves-light btn"  %>
    </div>
  </div>
</div>